# Generated by Django 5.2 on 2026-03-30 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('inversion_entrada', 'Inversión entrada'), ('inversion_salida', 'Inversión salida'), ('retiro', 'Retiro'), ('ajuste', 'Ajuste')], db_index=True, max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=0, help_text='Positivo = entrada de dinero, Negativo = salida', max_digits=14)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento financiero',
                'verbose_name_plural': 'Movimientos financieros',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
