# Generated by Django 5.2 on 2026-03-28 21:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('modelo_celular', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_costo', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_venta', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/')),
                ('imagen_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='inventario.producto')),
                ('cantidad', models.IntegerField(default=0)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('ultima_venta', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock actual',
                'verbose_name_plural': 'Stock actual',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada_compra', 'Entrada por compra'), ('salida_venta', 'Salida por venta'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('devolucion_venta', 'Devolución de venta'), ('devolucion_compra', 'Devolución a proveedor')], max_length=30)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_posterior', models.IntegerField()),
                ('referencia_tipo', models.CharField(blank=True, max_length=30)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-creado_en'],
            },
        ),
    ]
