# Generated by Django 5.2 on 2026-03-28 21:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('fecha', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('moneda', models.CharField(choices=[('PYG', 'Guaraníes'), ('USD', 'Dólares'), ('BRL', 'Reales')], default='PYG', max_length=5)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('nro_factura', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AdicionalCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Detalle opcional, ej: Transportista Pérez', max_length=200)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adicionales_compra', to='gastos.conceptoadicional')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionales', to='compras.compra')),
            ],
            options={
                'verbose_name': 'Adicional de compra',
                'verbose_name_plural': 'Adicionales de compra',
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_compra', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Ítem de compra',
                'verbose_name_plural': 'Ítems de compra',
            },
        ),
    ]
