# Generated by Django 5.2 on 2026-03-28 21:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('egreso', 'Egreso (costo)'), ('ingreso', 'Ingreso')], default='egreso', max_length=10)),
                ('aplica_a', models.CharField(choices=[('compra', 'Compras'), ('venta', 'Ventas'), ('gasto', 'Gasto general'), ('todos', 'Todos')], default='todos', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concepto adicional',
                'verbose_name_plural': 'Conceptos adicionales',
                'ordering': ['aplica_a', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GastoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Detalle específico del gasto', max_length=200)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(db_index=True)),
                ('comprobante', models.CharField(blank=True, help_text='Número de factura o recibo', max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.conceptoadicional')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto general',
                'verbose_name_plural': 'Gastos generales',
                'ordering': ['-fecha'],
            },
        ),
    ]
