# Generated by Django 5.2 on 2026-03-28 21:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('telefono', models.CharField(blank=True, db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('cliente_telefono', models.CharField(blank=True, max_length=30)),
                ('fecha', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('preparando', 'Preparando'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('devuelta', 'Devuelta')], db_index=True, default='confirmada', max_length=20)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('ecommerce', 'Tienda online'), ('presencial', 'Presencial'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('otro', 'Otro')], default='whatsapp', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_unitario', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje (0-100)', max_digits=5)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_venta', to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Ítem de venta',
                'verbose_name_plural': 'Ítems de venta',
            },
        ),
        migrations.CreateModel(
            name='AdicionalVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Detalle opcional, ej: PedidosYa zona Central', max_length=200)),
                ('monto', models.DecimalField(decimal_places=0, help_text='Positivo=ingreso, Negativo=descuento/egreso', max_digits=10)),
                ('a_cargo_de', models.CharField(choices=[('cliente', 'Lo paga el cliente'), ('negocio', 'Lo asume el negocio')], default='cliente', max_length=10)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adicionales_venta', to='gastos.conceptoadicional')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionales', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Adicional de venta',
                'verbose_name_plural': 'Adicionales de venta',
            },
        ),
    ]
