# Generated by Django 5.2 on 2026-03-28 21:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoWeb',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='producto_web', serialize=False, to='inventario.producto')),
                ('titulo_web', models.CharField(blank=True, max_length=200)),
                ('descripcion_web', models.TextField(blank=True)),
                ('precio_web', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('visible', models.BooleanField(db_index=True, default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto (tienda)',
                'verbose_name_plural': 'Productos (tienda)',
                'ordering': ['orden', 'producto__codigo'],
            },
        ),
        migrations.CreateModel(
            name='ItemPromoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PromoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promos/%Y/%m/')),
                ('imagen_url', models.URLField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('productos', models.ManyToManyField(related_name='promos', through='ecommerce.ItemPromoWeb', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
            },
        ),
        migrations.CreateModel(
            name='PedidoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.CharField(db_index=True, max_length=20, unique=True)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_telefono', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('pendiente_contacto', 'Pendiente contacto'), ('pendiente_pago', 'Pendiente pago'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente_contacto', max_length=25)),
                ('tipo_pedido', models.CharField(choices=[('producto', 'Producto'), ('promo', 'Promo')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('whatsapp_url', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_web', to='inventario.producto')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_web', to='ecommerce.promoweb')),
            ],
            options={
                'verbose_name': 'Pedido web',
                'verbose_name_plural': 'Pedidos web',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='itempromoweb',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.promoweb'),
        ),
        migrations.AlterUniqueTogether(
            name='itempromoweb',
            unique_together={('promo', 'producto')},
        ),
    ]
